<?php
/**
 * 内容模板
 * @var \Weline\Framework\View\Template $this
 */
?>
<!-- start page title -->
<div class='row'>
    <div class='col-12'>
        <div class='page-title-box d-sm-flex align-items-center justify-content-between'>
            <h4 class='mb-sm-0'>
                <lang>Acl权限管理</lang>
            </h4>

            <div class='page-title-right'>
                <ol class='breadcrumb m-0'>
                    <li class='breadcrumb-item'>
                        <a href='javascript: void(0);'>
                            <lang>系统配置</lang>
                        </a>
                    </li>
                    <li class='breadcrumb-item'>
                        <a href="@backend-url('*/backend/acl')"><lang>Acl权限管理</lang></a>
                    </li>
                    <li class='breadcrumb-item'>
                        <a href="@backend-url('*/backend/acl/role')"><lang>Acl角色管理</lang></a>
                    </li>
                    <li class='breadcrumb-item active'>
                        <lang>Acl角色添加</lang>
                    </li>
                </ol>
            </div>

        </div>
    </div>
</div>
<!-- end page title -->
<!-- start page message -->
<div class='row'>
    <template>Weline_Component::message.phtml</template>
</div> <!-- end message -->
<div class='row'>
    <div class='col-12'>
        <div class='card'>
            <div class='card-body'>
                <h4 class='card-title'>
                    <lang>Acl权限管理</lang>
                </h4>
                <p class='card-title-desc'>
                    <lang>支持角色权限管理</lang>
                </p>
                <form class='needs-validation' action="{{action}}" method="post"
                      novalidate>
                    <div class='row'>
                        <div class='col-md-6'>
                            <div class='mb-3'>
                                <label class='form-label' for='role_name'><lang>角色名</lang></label>
                                <if condition="edit_role.role_id">
                                    <input type='hidden' name="role_id" value='{{edit_role.role_id}}'>
                                </if>
                                <input type='text' class='form-control' name="role_name" id='role_name'
                                       placeholder='@lang{请输入角色名}' value='{{edit_role.role_name}}'
                                       required>
                                <div class='valid-feedback'>
                                    <lang>角色名称验证成功</lang>
                                </div>
                                <div class='invalid-feedback'>
                                    <lang>请输入角色名称</lang>
                                </div>
                            </div>
                        </div>
                        <div class='col-md-6'>
                            <div class='mb-3'>
                                <label class='form-label' for='role_description'><lang>角色描述</lang></label>
                                <textarea type='text' class='form-control' name="role_description" id='role_description'
                                       placeholder='@lang{请输入角色描述}'
                                          required>{{edit_role.role_description}}</textarea>
                                <div class='valid-feedback'>
                                    <lang>角色描述验证成功</lang>
                                </div>
                                <div class='invalid-feedback'>
                                    <lang>请输入角色描述</lang>
                                </div>
                            </div>
                        </div>
                    </div>
                    <button type='submit' class='btn btn-primary'><lang>提交</lang></button>
                </form>
            </div>
        </div>
    </div> <!-- end col -->
</div> <!-- end row -->
