<?php
/**
 * 内容模板
 * @var \Weline\Framework\View\Template $this
 */
?>
<link rel='stylesheet' type='text/css' href='@static(Weline_Acl::libs/Groupable-Searchable-Dual-Listbox-Transfer/icon_font/css/icon_font.css)'/>
<link rel='stylesheet' type='text/css' href='@static(Weline_Acl::libs/Groupable-Searchable-Dual-Listbox-Transfer/css/jquery.transfer.css?v=0.0.3)'/>

<!-- start page title -->
<div class='row'>
    <div class='col-12'>
        <div class='page-title-box d-sm-flex align-items-center justify-content-between'>
            <h4 class='mb-sm-0'>
                <lang>Acl权限管理</lang>
            </h4>

            <div class='page-title-right'>
                <ol class='breadcrumb m-0'>
                    <li class='breadcrumb-item'><a href='javascript: void(0);'>
                            <lang>系统配置</lang>
                        </a></li>
                    <li class='breadcrumb-item active'>
                        <lang>Acl权限管理</lang>
                    </li>
                </ol>
            </div>

        </div>
    </div>
</div>
<!-- end page title -->

<div class='row'>
    <template>Weline_Component::message.phtml</template>
</div>

<div class='row'>
    <div class='col-12'>
        <div class='card'>
            <div class='card-body'>

                <h4 class='card-title'>
                    <lang>Acl权限管理</lang>
                </h4>
                <p class='card-title-desc'>
                    <lang>支持角色权限管理</lang>
                </p>
                <!--双向选择列表-->

            </div>
        </div>
    </div> <!-- end col -->
</div> <!-- end row -->

<script>
(function() {
    'use strict';
    
    var groupDataArray1 = [
        {
            'groupName': 'China',
            'groupData': [
                {'city': 'Beijing', 'value': 122},
                {'city': 'Shanghai', 'value': 643},
                {'city': 'Qingdao', 'value': 422},
                {'city': 'Tianjin', 'value': 622}
            ]
        },
        {
            'groupName': 'Japan',
            'groupData': [
                {'city': 'Tokyo', 'value': 132},
                {'city': 'Osaka', 'value': 112},
                {'city': 'Yokohama', 'value': 191}
            ]
        }
    ];

    var settings3 = {
        'groupDataArray': groupDataArray1,
        'groupItemName': 'groupName',
        'groupArrayName': 'groupData',
        'itemName': 'city',
        'valueName': 'value',
        'callable': function (items) {
            console.dir(items)
        }
    };

    $('#transfer3').transfer(settings3);
})();
</script>
